In [2]:
import numpy as np
import pandas as pd
from math import sqrt
import matplotlib.pyplot as plt

G = 6.67e-11 # (m^3)/(kg * s^2)
AU = 1.495978707 * 10e11 # astronomical unit in meters


class Star():
    def __init__(self,x_pos,y_pos,x_vel,y_vel, mass):
        self.pos = np.array([x_pos,y_pos])*AU # position vector (units in AU)
        self.vel = np.array([x_vel,y_vel]) # velocity vector (units in m/s)
        
        self.x_pos = self.pos[0]
        self.y_pos = self.pos[1]
        self.x_vel = self.vel[0]
        self.y_pos = self.vel[1]
        
        self.mass = mass # star mass (units in kg)

In [3]:
def norm(vector):
    '''Returns normalised vector of a 2-D vector'''
    norm = vector/ sqrt(vector[0]**2 + vector[1]**2)
    return norm

def mag(vector):
    ''' Returns magnitude of a 2-D vector'''
    mag = sqrt(vector[0]**2 + vector[1]**2)
    return mag

In [4]:
g_star = Star(0, 0, 0, 0, 1.989e30)
k_star = Star(1.00269*AU, 0, 0, 36434.5, 0.5*g_star.mass)
t = 0
dt = 8450

In [5]:
r = k_star.pos - g_star.pos
R = mag(r)

In [6]:
36e6/84600

425.531914893617

In [7]:
df = pd.DataFrame()

In [8]:
ans = []
count = 0
while t < 36e6:
    r= k_star.pos - g_star.pos
    R = mag(r)
    F_x = G * (k_star.mass * g_star.mass/R**2) * (r[0]/R)
    F_y = G * (k_star.mass * g_star.mass/R**2) * (r[1]/R)
    k_vel_x = k_star.vel[0]
    k_vel_y = k_star.vel[1]
    k_vel_x = k_vel_x + G*(k_star.mass/R**2)* (k_star.pos[0]/R)
    k_vel_y = k_vel_y + G*(k_star.mass/R**2)* (k_star.pos[1]/R)
    
    ans.append([k_vel_x, k_vel_y])
    
    
    
    count += 1
    ans.append(r)
    t += dt

In [9]:
count

4261

In [10]:
ans

[[1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00000000e+00]),
 [1.3173331048055415e-29, 36434.5],
 array([2.24397238e+24, 0.00