In [18]:
import numpy as np
import pandas as pd
from math import sqrt
import matplotlib.pyplot as plt

G = 6.67e-11 # (m^3)/(kg * s^2)
AU = 1.495978707 * 10e11 # astronomical unit in meters



class Star():
    def __init__(self,x_pos,y_pos,x_vel,y_vel, mass):
        self.pos = np.array([x_pos*AU,y_pos]) # position vector (units in AU)
        self.vel = np.array([x_vel,y_vel]) # velocity vector (units in m/s)
        
        self.x_pos = self.pos[0]
        self.y_pos = self.pos[1]
        self.x_vel = self.vel[0]
        self.y_pos = self.vel[1]
        
        self.mass = mass # star mass (units in kg)

In [31]:
def norm(vector):
    '''Returns normalised vector of a 2-D vector'''
    norm = vector/ sqrt(vector[0]**2 + vector[1]**2)
    return norm

def mag(vector):
    ''' Returns magnitude of a 2-D vector'''
    mag = sqrt(vector[0]**2 + vector[1]**2)
    return mag

In [32]:
init_dist = 1.00269*AU
g_star = Star(0, 0, 0, 0, 1.989e30)
k_star = Star(init_dist, 0, 0, 36434.5, 0.5*g_star.mass)

In [33]:
 init_dist = 1.00269*AU

In [34]:
k_star.pos

array([2.24397238e+24, 0.00000000e+00])

In [42]:
1.00269*AU == 2.24397238e+24


False

In [35]:
g_star.pos

array([0., 0.])

In [36]:
r = k_star.pos - g_star.pos
R = mag(r)

In [37]:
r

array([2.24397238e+24, 0.00000000e+00])

In [38]:
F = G * (g_star.mass * k_star.mass/R**2)
F

26.20175545458222

In [39]:
(1.00269*1.495978707e11)

150000288972.183

In [40]:
F = 6.67e-11 * ((1.989e30)*(0.5*1.989e30)/(1.00269*1.495978707e11)**2)

In [41]:
F

5.863827866869709e+27